server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://dpg-cp2nnf63e1ms73f2ip40-a.singapore-postgres.render.com/dbbanking_mobile
    username: admin
    password: VRD8GjmA8ecv4ktpboDCiKePFrJTld9v
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  prefix: /api

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace